package routers

import (
	"boss/controllers"
	beego "github.com/beego/beego/v2/server/web"
)

func init() {
	//beego.Router("/", &controllers.PageController{}, "*:Index")
	//添加过滤函数
	beego.Router("/filter.html", &controllers.FilterController{}, "*:Filter")
	//登录验证接口
	beego.Router("/login", &controllers.LoginController{}, "*:Login")
	beego.Router("/logout", &controllers.LoginController{}, "*:Logout")
	beego.Router("/getVerifyImg", &controllers.LoginController{}, "*:GetVerifyImg")
	beego.Router("/update/password", &controllers.UpdateController{}, "*:UpdatePassword")
	beego.Router("/freeze/operator", &controllers.UpdateController{}, "*:FreezeOperator")
	beego.Router("/freeze/merchant", &controllers.UpdateController{}, "*:UpdateMerchantStatus")
	beego.Router("/unfreeze/operator", &controllers.UpdateController{}, "*:UnfreezeOperator")
	beego.Router("/unfreeze/merchant", &controllers.UpdateController{}, "*:UpdateMerchantStatus")
	beego.Router("/edit/operator", &controllers.UpdateController{}, "*:EditOperator")
	beego.Router("/add/menu", &controllers.AddController{}, "*:AddMenu")
	beego.Router("/add/secondMenu", &controllers.AddController{}, "*:AddSecondMenu")
	beego.Router("/add/power", &controllers.AddController{}, "*:AddPower")
	beego.Router("/add/role", &controllers.AddController{}, "*:AddRole")
	beego.Router("/add/operator", &controllers.AddController{}, "*:AddOperator")
	beego.Router("/add/bankCard", &controllers.AddController{}, "*:AddBankCard")
	beego.Router("/add/road", &controllers.AddController{}, "*:AddRoad")
	beego.Router("/add/roadPool", &controllers.AddController{}, "*:AddRoadPool")
	beego.Router("/add/merchant", &controllers.AddController{}, "*:AddMerchant")
	beego.Router("/add/agent", &controllers.AddController{}, "*:AddAgent")
	beego.Router("/add/merchant/deploy", &controllers.AddController{}, "*:AddMerchantDeploy")
	beego.Router("/add/merchant/payType", &controllers.AddController{}, "*:AddMerchantPayType")
	beego.Router("/add/payfor", &controllers.AddController{}, "*:AddPayFor")
	beego.Router("/add/self/payfor", &controllers.AddController{}, "*:AddSelfPayFor")
	beego.Router("/get/menu", &controllers.GetController{}, "*:GetMenu")
	beego.Router("/get/secondMenu", &controllers.GetController{}, "*:GetSecondMenu")
	beego.Router("/get/secondMenus", &controllers.GetController{}, "*:GetSecondMenus")
	beego.Router("/get/oneMenu", &controllers.GetController{}, "*:GetOneMenu")
	beego.Router("/get/firstMenu", &controllers.GetController{}, "*:GetFirstMenu")
	beego.Router("/get/powerItem", &controllers.GetController{}, "*:GetPowerItem")
	beego.Router("/get/role", &controllers.GetController{}, "*:GetRole")
	beego.Router("/get/allRole", &controllers.GetController{}, "*:GetAllRole")
	beego.Router("/get/deployTree", &controllers.GetController{}, "*:GetDeployTree")
	beego.Router("/get/operator", &controllers.GetController{}, "*:GetOperator")
	beego.Router("/get/oneOperator", &controllers.GetController{}, "*:GetOneOperator")
	beego.Router("/get/editOperator", &controllers.GetController{}, "*:GetEditOperator")
	beego.Router("/get/bankCard", &controllers.GetController{}, "*:GetBankCard")
	beego.Router("/get/oneBankCard", &controllers.GetController{}, "*:GetOneBankCard")
	beego.Router("/get/road", &controllers.GetController{}, "*:GetRoad")
	beego.Router("/get/oneRoad", &controllers.GetController{}, "*:GetOneRoad")
	beego.Router("/get/all/road", &controllers.GetController{}, "*:GetAllRoad")
	beego.Router("/get/roadPool", &controllers.GetController{}, "*:GetRoadPool")
	beego.Router("/get/all/roll/pool", &controllers.GetController{}, "*:GetAllRollPool")
	beego.Router("/get/merchant", &controllers.GetController{}, "*:GetMerchant")
	beego.Router("/get/all/merchant", &controllers.GetController{}, "*:GetAllMerchant")
	beego.Router("/get/one/merchant", &controllers.GetController{}, "*:GetOneMerchant")
	beego.Router("/get/one/merchant/deploy", &controllers.GetController{}, "*:GetOneMerchantDeploy")
	beego.Router("/get/all/account", &controllers.GetController{}, "*:GetAllAccount")
	beego.Router("/get/account", &controllers.GetController{}, "*:GetAccount")
	beego.Router("/get/one/account", &controllers.GetController{}, "*:GetOneAccount")
	beego.Router("/get/account/history", &controllers.GetController{}, "*:GetAccountHistory")
	beego.Router("/get/agent", &controllers.GetController{}, "*:GetAgent")
	beego.Router("/get/all/agent", &controllers.GetController{}, "*:GetAllAgent")
	beego.Router("/get/product", &controllers.GetController{}, "*:GetProduct")
	beego.Router("/get/order", &controllers.GetController{}, "*:GetOrder")
	beego.Router("/get/one/order", &controllers.GetController{}, "*:GetOneOrder")
	beego.Router("/get/orderProfit", &controllers.GetController{}, "*:GetOrderProfit")
	beego.Router("/get/payfor", &controllers.GetController{}, "*:GetPayFor")
	beego.Router("/get/one/payfor", &controllers.GetController{}, "*:GetOnePayFor")
	beego.Router("/get/balance", &controllers.GetController{}, "*:GetBalance")
	beego.Router("/get/notify/bankOrderId/list", &controllers.GetController{}, "*:GetNotifyBankOrderIdList")
	beego.Router("/get/agent/to/merchant", &controllers.GetController{}, "*:GetAgentToMerchant")
	beego.Router("/get/profit", &controllers.GetController{}, "*:GetProfit")
	beego.Router("/save/power", &controllers.AddController{}, "*:SavePower")
	beego.Router("/save/roadUid", &controllers.AddController{}, "*:SaveRoadUid")
	beego.Router("/up/menu", &controllers.UpdateController{}, "*:UpMenu")
	beego.Router("/down/menu", &controllers.UpdateController{}, "*:DownMenu")
	beego.Router("/up/secondMenu", &controllers.UpdateController{}, "*:UpSecondMenu")
	beego.Router("/down/secondMenu", &controllers.UpdateController{}, "*:DownSecondMenu")
	beego.Router("/update/roadStatus", &controllers.UpdateController{}, "*:UpdateRoadStatus")
	beego.Router("/update/account/status", &controllers.UpdateController{}, "*:UpdateAccountStatus")
	beego.Router("/update/agent/status", &controllers.UpdateController{}, "*:UpdateAgentStatus")
	beego.Router("/update/order/status", &controllers.UpdateController{}, "*:UpdateOrderStatus")
	beego.Router("/account/operator", &controllers.UpdateController{}, "*:OperatorAccount")
	beego.Router("/delete/menu", &controllers.Deletecontroller{}, "*:DeleteMenu")
	beego.Router("/delete/secondMenu", &controllers.Deletecontroller{}, "*:DeleteSecondMenu")
	beego.Router("/delete/powerItem", &controllers.Deletecontroller{}, "*:DeletePowerItem")
	beego.Router("/delete/role", &controllers.Deletecontroller{}, "*:DeleteRole")
	beego.Router("/delete/operator", &controllers.Deletecontroller{}, "*:DeleteOperator")
	beego.Router("/delete/bankCardRecord", &controllers.Deletecontroller{}, "*:DeleteBankCardRecord")
	beego.Router("/delete/road", &controllers.Deletecontroller{}, "*:DeleteRoad")
	beego.Router("/delete/roadPool", &controllers.Deletecontroller{}, "*:DeleteRoadPool")
	beego.Router("/delete/merchant", &controllers.Deletecontroller{}, "*:DeleteMerchant")
	beego.Router("/delete/account", &controllers.Deletecontroller{}, "*:DeleteAccount")
	beego.Router("/delete/agent", &controllers.Deletecontroller{}, "*:DeleteAgent")
	beego.Router("/delete/agent/merchant/relation", &controllers.Deletecontroller{}, "*:DeleteAgentRelation")
	beego.Router("/reset/agent/password", &controllers.UpdateController{}, "*:ResetAgentPassword")
	beego.Router("/supplier/order/query", &controllers.SupplierQuery{}, "*:SupplierOrderQuery")
	beego.Router("/supplier/payfor/query", &controllers.SupplierQuery{}, "*:SupplierPayForQuery")
	beego.Router("/choose/payfor/road", &controllers.UpdateController{}, "*:ChoosePayForRoad")
	beego.Router("/result/payfor", &controllers.UpdateController{}, "*:ResultPayFor")
	beego.Router("/send/notify", &controllers.SendNotify{}, "*:SendNotifyToMerchant")
	beego.Router("/self/send/notify", &controllers.SendNotify{}, "*:SelfSendNotify")
}
